### PR TITLE
Add confirmation check for deploy

### LINKED ISSUE #266: Add warnings when deploying
Look into ways of warning when deploying via Capistrano.

- Message containing the project name, branch being pushed, user, etc
- Verification of approval for deployment
- Etc.

### PR DESCRIPTION
**Pull request by crowesn**
Resolves #266

### CODE REVIEW

**Review by scherztc — CHANGES_REQUESTED** [review]
This is good but after talking with Glenn, we want one more variable in the echo section.

Deploying #{@branch} to #{@stage} servers.

and

we want one more if then stating

WARN
    ask :value, "Have you submitted your Change Management Request? (Y)"

**Comment by crowesn** [comment]
@scherztc This should be ready to rock.

Screen Shot 2023-05-03 at 10 34 39 AM

**Review by hortongn — CHANGES_REQUESTED** [review]
We want to make sure someone has an *approved* change request.  If possible, the prompt for having an approved change should only show when we're deploying to production.

**Comment by crowesn** [comment]
Change request confirmation now only files on production deploys.

Screen Shot 2023-05-09 at 5 22 23 PM

**Comment by hortongn** [comment]
@scherztc please merge this if it looks good to you.

**Pull request merged**
