### PR TITLE
Destroys Change Management Record when destroying Software Record.

### LINKED ISSUE #336: Deleting software records with attached change requests throws an error
If a user attempts to delete a software record that has one or more linked change requests, the application will error.  

Discuss how to handle the change requests in this circumstance.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #336

### CODE REVIEW

**Comment by hortongn** [comment]
@scherztc I think it would be worth updating this exiting SoftwareRecord delete test to verify that it deletes an attached change request with the software record:
https://github.com/uclibs/application_portfolio/blob/qa/spec/controllers/software_records_controller_spec.rb#L396-L401

**Comment by scherztc** [comment]
The Software Record delete test has been updated to account for the ChangeRequest.

**Review by hortongn — CHANGES_REQUESTED** [review]
@scherztc You need an expect statement that verifies the change request has been deleted.

**Comment by scherztc** [comment]
@hortongn :  Initially, I thought that the SoftwareRecord test was enough, since it wouldn't actually pass if our code was wrong.  After your feedback, I added another test that also checks for the deletion of the ChangeRequest.  It should be good, now.

**Review by hortongn — APPROVED** [review]
@scherztc Thanks for adding the test!

**Pull request merged**
